name: wethr
base: core18
version: '0.1'
summary:  Command line weather tool
description: |
  Get current weather:-
    $ wethr
  Get  current weather in metric units
    $wethr --metric

  Get current weather in imperial units
    $wethr --imperial

grade: stable
confinement: strict


apps:
  wethr:
    command: wethr
    plugs:
      - network


parts:
  wethr:
    # See 'snapcraft plugins'
    plugin: nodejs
    nodejs-version: 12.18.4
    source: https://github.com/twobucks/wethr.git
